"""empty message

Revision ID: 24aab18c7ecd
Revises: 6e30140db687
Create Date: 2021-12-17 00:54:21.058044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24aab18c7ecd'
down_revision = '6e30140db687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=4), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('sell', 'buy', name='operationtypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_symbol'), 'operation', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_symbol'), table_name='operation')
    op.drop_table('operation')
    # ### end Alembic commands ###
