"""initial migration

Revision ID: 6e30140db687
Revises: 
Create Date: 2021-12-16 21:35:25.386053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e30140db687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=4), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('profit_percent', sa.Float(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('price_ave', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_symbol'), 'stock', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_symbol'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
